### ISSUE TITLE
Add sound effects

### ISSUE THREAD

**Issue by simpl-r** [MuseApplications/MyFunGame#42]
I'm going to hunt for sound effects.

**Comment by simpl-r** [comment]
I've obtained all sound effects I think we'll need except for the volcano explosion (Randal is helping me with that one, I think) and the clapping, which I'll record maybe tomorrow.

**Comment by rkamradt** [comment]
Where do you want the auditoriumhum and scary sound effects to come in?

**Comment by simpl-r** [comment]
I was thinking that we could have the auditorium hum going on through the scene, but actually I'm not sure if you can have two tracks simultaneously? Plus there's the blue ribbon sound?

As for the scary sound effect, I though we could try it with the gloved hand. 

I'm not sure if they're the best sound effects, but I did what I could.

School bell is for the very first panel.
