### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by simpl-r** [MuseApplications/MyFunGame#44]
I don't see the new font. What's going on?

**Comment by rkamradt** [comment]
I added the font as the dialog font as well as the gui font. Let me know if it works for you

**Comment by simpl-r** [comment]
It's working on the text, but the character headings and the main screen show the default text. Any way to get everything in the game to be in this new font? (other than the speech bubbles, of course)

**Comment by rkamradt** [comment]
I added the font to the wrong file, so it got overridden. Try it again.

**Comment by simpl-r** [comment]
Yay, it came through on my end!
