### ISSUE TITLE
Outside Jacqueline's House

### ISSUE THREAD

**Issue by simpl-r** [MuseApplications/MyFunGame#52]
Let's cut the music for this section, until she enter's Jacqueline's house, and add in a creepy wind sound effect for that first panel outside of the house. I'll go find one.

**Comment by simpl-r** [comment]
Okay, found it. So, stop the music at the panel after Ruby discovers the mail for Jacqueline, insert creepy wind.mp3 there, then resume the music once Ruby is inside the house.

**Comment by simpl-r** [comment]
I still think the music better off resumed once Ruby is fully inside the house. Can we try that?

**Comment by rkamradt** [comment]
Done. See what you think
