### ISSUE TITLE
Sprite changes

### ISSUE THREAD

**Issue by simpl-r** [MuseApplications/MyFunGame#53]
The sprites in these panels need to be changed. I've indicated all changes-- if nothing is indicated for a specific panel, then it should remain as is.

Ruby
1.0 rubyspritefullhappy
1.1 rubyspritefullhappy “Hi, I’m Ruby. I’m a normal teenager.”
1.2 “
1.3 “
1.4 ”
1.5 rubyspritefullneutral “Actually, they’re not really my friends.”
1.6 rubyspritefullhappy “This is my only real friend, Mia.”
1.7 rubyspritefullwhateva “Most of my electronic projects don’t work.”
1.12 rubyspritefullwhateva “I mostly fell on my butt. I don’t know why I tried bowling, I’m pretty terrible at sports.”
1.17 rubyspritefullwhateva “Only Mia clapped, and even she stopped when she noticed no one else was clapping.”

2.4 rubyspritefullwhateva “I don’t know if she even has a job. I’ve seen her leave the house maybe two or three times, ever.”

3.3 rubyspritehalfwhateva “Not that kind of pie! A P-I pi. It’s like a little computer.”
3.4 “
3.5 rubyspritehalfhappy Decision 2
3.6 rubyspritehalfhappy “That’s a great idea! I’m glad I thought of it!”
3.6b rubyspritehalfhappy “That’s a great idea! You’re a genius, Mia!”
3.6c rubyspritehalfannoyed “Wait what? Uh, yeah, no, let’s just forget this ever popped in my head.”
3.7 rubyspritehalfhappy “…”
3.8 rubyspritehalfneutral “You know the science fair is tomorrow, can you do it by then?”
3.9 “
3.10 “
3.11 “
3.12 “
3.15 rubyspritehalfneutral “Sure, what can it hurt? Let’s give it a shot”
3.16 "
3.17 “

4.4 rubyspritefullwhateva “Oh no, here are the judges. Okay Ruby time to show them what you’re made of.”
4.5 “
4.8 rubyspritefullhappy “Hey Ruby, congrats on your win.”
4.9 rubyspritefullneutral
4.10 rubyspritefullwhateva “You know, I think we got off on the wrong foot. I find your scrappy approach admirable.”
4.11 rubyspritefullneutral2
4.12 “
4.13 “
4.14 rubyspritefullannoyed “Suddenly John’s volcano erupts again!”
4.15 rubyspritefullneutral
4.22 Decision 3
4.24b rubyspritefullannoyed
4.23c rubyspritefullannoyed “NO WHAT STOP”
4.24c “
4.29 rubyspritefullneutral “There’s already a robotic vacuum!”

Mia
3.1 miaspritehalfchill “I bet if I hooked this up with my Raspberry Pi I could make it move. But what should it do?”
3.2 miaspritehalfhappy
3.3 miaspritehalfchill
3.4 miaspritehalfworry
3.5 “ Decision
3.8 miaspritehalfchill “You know the science fair is tomorrow, an you do it by then?
3.9 “
3.10 “
3.11 “
3.12 miaspritehalfworry “I’ll get some energy drinks, it sounds like it will be a long night.”
3.13 miaspritehalfchill

4.16 miaspritefullworry “I wasn’t sure how to rescue you, so I put more baking soda in the volcano.”
4.17 miaspritefullhappy
4.18 miaspritefullchill
4.19 “
4.20 “
4.21 miaspritefullworry “As a matter of fact…”
4.22 “ Decision 3
4.23a miaspritefullhappy
4.23b miaspritefullcry2
4.24b miaspritefullcry1
4.23c miaspritefullworry
4.24c “
4.25 miaspritefullworry “It - it was me, ma’am.”
4.26 miaspritefullchill

Jacqueline
2.15 jackiespritefullhappy “Erector! Erector come down and meet this young lady.”
2.19 jackiespritefullhappy “Yes, my specialty is mechanical hands, would you like one? It doesn’t actually do anything.”

4.18 jackiespritefullchill “I see you put my mechanical hand to good use.”
4.19 “
4.20 “
4.21 “
4.22 “
4.23abc “
4.24bc “
4.25 “
4.28 jackiespritefullchill “No one is an expert at everything…”
4.29 “

John
no notes

**Comment by yugyfoog** [comment]
Panel 1.0 is baked.  I'll try to fix others.

**Comment by simpl-r** [comment]
It looks good! There’s just a funny thing in scene 3, and small thing in scene 4.

basically all the sprites in panels 3.5-3.12 need to be half, not full
panel 3.5 Decision 1, you need rubyspritehalfhappy (as opposed to full)
3.6a “ “That’s a great idea! Glad I thought of it” (also there’s a misspelling in this sentence)
3.6b “ “That’s a great idea! You’re a genius, Mia!”
3.6c rubyspritehalfannoyed
3.7 rubyspritehalfhappy “…”
3.8 “
3.9 “
3.10 “
3.11 “
3.12 “

4.3 still shows rubyspritefullannoyed, right after john’s volcano explosion. Let’s change that to rubyspritefullwhateva

**Comment by rkamradt** [comment]
There's still an issue with sprites not changing if the scene goes on too long, I'll make a new issue and close this one.
