### ISSUE TITLE
Sprites don't change on longer scenes.

### ISSUE THREAD

**Issue by rkamradt** [MuseApplications/MyFunGame#54]
I think we need to hide previous sprites before we can show new ones, perhaps there are too many layers. On some of the longer scenes, the expressions stop changing.

**Comment by yugyfoog** [comment]
The hiding of images should be automatic. I guess we since we abandoned the file name conventions the system got confused.

**Comment by yugyfoog** [comment]
If anyone has any more specific info on where the problem is I'll try to fix them. Don't give me panel number because that doesn't help, quote the dialog.

**Comment by rkamradt** [comment]
what file name conventions did we abandon?

**Comment by yugyfoog** [comment]
Character image files should be <name><space><attributes>, e.g., "ruby full happy".

**Comment by rkamradt** [comment]
Well, you should have mentioned that earlier :/

**Comment by rkamradt** [comment]
Changed all names to match conventions
